[[language]]
name="python"
roots = ["pyproject.toml", "setup.py", "Poetry.lock", ".git"]
language-server = { command = "pyright-ls-helix"}
# language-server = { command = "pyright-langserver", args = ["--stdio"]}
# config = { analysis = { autoImportCompletions = false, typeCheckingMode = "strict", diagnosticMode = "openFilesOnly" }}
# config = { reportUnusedImport = "warning", reportUnusedClass = "warning", reportUnusedFunction = "warning", reportUnusedVariable = "warning"}
config = {}
# config = ""
auto-format = true
formatter = {command = "black", args = ["--quiet", "-"]}
indent = { tab-width = 4, unit = "    "}

[[grammar]]
name = "python"
source = { git = "https://github.com/tree-sitter/tree-sitter-python", rev = "2b9e9e0d231d5dd9f491d47f704817baee7d5af0"}

[[language]]
name="toml"
# language-server = { command = "taplo", args = ["lsp", "stdio"]}
language-server = { command = ""}

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }
indent = { tab-width = 2, unit = "  "}

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser", "markdown"]}

[[language]]
name = "bash"
indent = { tab-width = 2, unit = "  "}
